site_name: NAC OPs Docs
theme:
  name: material
  palette:
    primary: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
  logo: assets/NAC_grey_4.png

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎

copyright: Copyright &copy; 2021 North Ayrshire Council


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/north-ayrshire-council

