site_name: NAC OPs Docs
theme:
  name: material
  palette:
    primary: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
  logo: assets/nac_2.png

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2021 North Ayrshire Council


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/north-ayrshire-council

